In [ ]:
# Broadcasting allows NumPy to perform operations on arrays
# with different shapes by virtually expanding dimensions
# so they match the larger array's shape.

# The dimensions have the same size.
# OR
# One of the dimensions has a size of 1.

#(4,3)
# | |
#(1,3)


# result =  matrix + vector.reshape((2,3))  # ValueError: cannot reshape array of size 2 into shape (2,3)
# print(result)

In [1]:
import numpy as np

In [2]:
# Example 1 : Scalar Broadcasting
a=np.array([1,2,3,4])
print(a+10)

[11 12 13 14]


In [ ]:
# Example 2 : 1D + 1D
x=np.array([1,2,3,4])
y=np.array([2,2,2,2])
print(x+y)

[3 4 5 6]


In [6]:
x*y

array([2, 4, 6, 8])

In [7]:
x/y

array([0.5, 1. , 1.5, 2. ])

In [8]:
x%y

array([1, 0, 1, 0])

In [9]:
# Example 3 : 2D + Scalar
a=np.array([[1,2],[3,4]])
a+10

array([[11, 12],
       [13, 14]])

In [11]:
x=np.array([[1,2],[3,4]])

y=np.array([[10,10],[10,10]])

x+y

array([[11, 12],
       [13, 14]])

In [12]:
# Example 2 : 1D + 1D
x=np.array([1,2,3,4])
y=np.array([2,2,2])
print(x+y)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [17]:
x=np.array([[1,2],[3,4]])

y=np.array([[10,10],[10,10]])

x+y

array([[11, 12],
       [13, 14]])

In [18]:
x=np.array([[1,2],[3,4]])

y=np.array([[10,10],[10,10]])

x*y

array([[10, 20],
       [30, 40]])

In [22]:
# Example 6 : 3D Broadcasting

a=np.ones((2,3,4))


b=np.array([1,2,3,4])

a+b

array([[[2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.]],

       [[2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.]]])

In [23]:
print(a.shape)
print(b.shape)

(2, 3, 4)
(4,)


In [ ]:
# (2,3,4)  ==>a
# (1,1,4)  ==>b

In [ ]:
a=np.ones((2,3,4))


b=np.array([[1,2,3,4],[1,2,3,4]])
print(b.shape)
#print(a+b)   #error

# (2,3,4) 
# (1,2,4) 

(2, 4)


ValueError: operands could not be broadcast together with shapes (2,3,4) (2,4) 

In [ ]:
a=np.ones((2,3,4))


b=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(b.shape)
print(a+b)   #error

# (2,3,4) 
# (1,3,4) 

(3, 4)
[[[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]

 [[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]]


In [27]:
a=np.ones((2,3,4))


b=np.array([[[1,2,3,4]],
            [[1,2,3,4]]])
print(b.shape)
print(a+b)   #error

# (2,3,4) 
# (2,1,4) 

(2, 1, 4)
[[[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]

 [[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]]
