NumPy append()<br>

append() is used to add elements at the end of an array.<br>

Syntax<br>
- np.append(arr, values, axis=None)<br>

Parameters<br>
- arr → Original array
- values → Value(s) to add
- axis → Dimension (optional)

In [2]:
# 1D Array
# Append Single Value
import numpy as np

a=np.array([1,2,3,4,5,6])

In [4]:
b= np.append(a,11)
b

array([ 1,  2,  3,  4,  5,  6, 11])

In [5]:
print(a)

[1 2 3 4 5 6]


In [6]:
b= np.append(a,[11,22,33])
b

array([ 1,  2,  3,  4,  5,  6, 11, 22, 33])

In [7]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
b= np.append(a,[11,22])
b

array([ 1,  2,  3,  4,  5,  6, 11, 22])

In [10]:
b= np.append(a,[[11,22]],axis=0)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 22]])

In [17]:
b= np.append(a,[[11],[22],[33]],axis=1)
b

array([[ 1,  2, 11],
       [ 3,  4, 22],
       [ 5,  6, 33]])

In [18]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
# Append Along height
b= np.append(a,[[[40,40]],[[40,40]],[[40,40]]],axis=1)
b

array([[[ 1,  2],
        [ 3,  4],
        [40, 40]],

       [[ 5,  6],
        [ 7,  8],
        [40, 40]],

       [[ 9, 10],
        [11, 12],
        [40, 40]]])

In [25]:
b= np.append(a,[[[40,40],[40,40]]],axis=0)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[40, 40],
        [40, 40]]])

In [26]:
b= np.append(a,[[[40],[40]],[[40],[40]],[[40],[40]]],axis=2)
b

array([[[ 1,  2, 40],
        [ 3,  4, 40]],

       [[ 5,  6, 40],
        [ 7,  8, 40]],

       [[ 9, 10, 40],
        [11, 12, 40]]])