NumPy split()
- split() is used to divide an array into multiple sub-arrays.

Syntax
- np.split(arr, indices_or_sections, axis=0)

Parameters
- arr → Input array
- indices_or_sections
- Number of equal parts
- OR list of split indices

axis
- 0 → Split rows (default)
- 1 → Split columns

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

###### 1D Array
###### Split into Equal Parts

In [3]:
b=np.split(a,2)
b

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [4]:
b=np.split(a,3)
b

ValueError: array split does not result in an equal division

In [5]:
b=np.split(a,4)
b

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [7]:
b[1]

array([3, 4])

In [ ]:
# Split at Specific Index
#          0  1 2 3 4 5 6 7
a=np.array([1,2,3,4,5,6,7,8])

b=np.split(a,[2,4])
b

[array([1, 2]), array([3, 4]), array([5, 6, 7, 8])]

In [9]:
# Split at Specific Index
#          0  1 2 3 4 5 6 7
a=np.array([1,2,3,4,5,6,7,8])

b=np.split(a,[2,4,7])
b

[array([1, 2]), array([3, 4]), array([5, 6, 7]), array([8])]

In [10]:
# 2D Array
a = np.array([[1,2],[3,4],[5,6],[7,8]])
# Split Rows (axis=0)
b=np.split(a,2,axis=0)
b

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [11]:
# 2D Array
a = np.array([[1,2],[3,4],[5,6],[7,8]])
# Split Rows (axis=0)
b=np.split(a,3,axis=0)
b

ValueError: array split does not result in an equal division

In [12]:
# 2D Array
a = np.array([[1,2],[3,4],[5,6],[7,8]])
# Split Rows (axis=0)
b=np.split(a,4,axis=0)
b

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

In [13]:
# 2D Array , specific split
a = np.array([[1,2],[3,4],[5,6],[7,8]])
# Split Rows (axis=0)
b=np.split(a,[1,3],axis=0)
b

[array([[1, 2]]),
 array([[3, 4],
        [5, 6]]),
 array([[7, 8]])]

In [14]:
# 2D Array
a = np.array([[1,2],[3,4],[5,6],[7,8]])
# Split columns (axis=1)
b=np.split(a,2,axis=1)
b

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [16]:
# 2D Array
a = np.array([[1,2,4],[3,4,4],[5,6,4],[7,8,4]])
# Split columns (axis=1)
b=np.split(a,3,axis=1)
b

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]]),
 array([[4],
        [4],
        [4],
        [4]])]

In [17]:
# 2D Array
a = np.array([[1,2,4,5],[3,4,4,5],[5,6,4,5],[7,8,4,5]])
# Split columns (axis=1)
b=np.split(a,[1,3],axis=1)
b

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2, 4],
        [4, 4],
        [6, 4],
        [8, 4]]),
 array([[5],
        [5],
        [5],
        [5]])]

In [20]:
# 3D Array
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
# Split Blocks (axis=0)
b=np.split(a,2,axis=0)
b

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])]

In [22]:
b[0]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [23]:
# Split rowa (axis=1)
b=np.split(a,2,axis=1)
b

ValueError: array split does not result in an equal division

In [24]:
# Split rowa (axis=1)
b=np.split(a,3,axis=1)
b

[array([[[ 0,  1,  2,  3]],
 
        [[12, 13, 14, 15]]]),
 array([[[ 4,  5,  6,  7]],
 
        [[16, 17, 18, 19]]]),
 array([[[ 8,  9, 10, 11]],
 
        [[20, 21, 22, 23]]])]

In [ ]:
# array([[[ 0,  1,  2,  3],         [[12, 13, 14, 15],
#         [ 4,  5,  6,  7],          [16, 17, 18, 19],
#         [ 8,  9, 10, 11]],          [20, 21, 22, 23]]])

In [25]:
# Split rowa (axis=1)
b=np.split(a,[1],axis=1)
b

[array([[[ 0,  1,  2,  3]],
 
        [[12, 13, 14, 15]]]),
 array([[[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])]

In [27]:
# Split Columns (axis=2)
b=np.split(a,2,axis=2)
b

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

In [28]:
# Split Columns (axis=2) , specific split
b=np.split(a,[1,3],axis=2)
b

[array([[[ 0],
         [ 4],
         [ 8]],
 
        [[12],
         [16],
         [20]]]),
 array([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],
 
        [[13, 14],
         [17, 18],
         [21, 22]]]),
 array([[[ 3],
         [ 7],
         [11]],
 
        [[15],
         [19],
         [23]]])]