In [1]:
import numpy as np

In [ ]:
# NumPy dsplit()
# - dsplit() is used to split an array depth-wise (along the 3rd axis / columns in a 3D array).

# Syntax
# - np.dsplit(arr, indices_or_sections)

# Parameters
# - arr → Input array
# - indices_or_sections
# - Number of equal parts
# - OR list of split indices

# Rules
# - ✅ Splits along axis=2.(blocks)
# - ✅ Works only with 3D or higher-dimensional arrays.
# - ✅ Size of the 3rd dimension must be divisible by the number of sections (for equal split).
# - ✅ Returns a list of arrays.
# - ✅ Original array is not modified.

In [2]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
b=np.dsplit(a,2)
b

[array([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],
 
        [[12, 13],
         [16, 17],
         [20, 21]]]),
 array([[[ 2,  3],
         [ 6,  7],
         [10, 11]],
 
        [[14, 15],
         [18, 19],
         [22, 23]]])]

In [5]:
b=np.dsplit(a,[1,3])
b

[array([[[ 0],
         [ 4],
         [ 8]],
 
        [[12],
         [16],
         [20]]]),
 array([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]],
 
        [[13, 14],
         [17, 18],
         [21, 22]]]),
 array([[[ 3],
         [ 7],
         [11]],
 
        [[15],
         [19],
         [23]]])]

In [6]:
b=np.dsplit(a,4)
b

[array([[[ 0],
         [ 4],
         [ 8]],
 
        [[12],
         [16],
         [20]]]),
 array([[[ 1],
         [ 5],
         [ 9]],
 
        [[13],
         [17],
         [21]]]),
 array([[[ 2],
         [ 6],
         [10]],
 
        [[14],
         [18],
         [22]]]),
 array([[[ 3],
         [ 7],
         [11]],
 
        [[15],
         [19],
         [23]]])]

In [7]:
a=np.arange(24).reshape(4,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [10]:
b=np.dsplit(a,[1])
b

[array([[[ 0],
         [ 3]],
 
        [[ 6],
         [ 9]],
 
        [[12],
         [15]],
 
        [[18],
         [21]]]),
 array([[[ 1,  2],
         [ 4,  5]],
 
        [[ 7,  8],
         [10, 11]],
 
        [[13, 14],
         [16, 17]],
 
        [[19, 20],
         [22, 23]]])]