NumPy concatenate()<br>

concatenate() is used to join two or more arrays.<br>

Syntax<br>
- np.concatenate((arr1, arr2), axis=0)<br>

Parameters
- arr1, arr2, ... → Arrays to join
- axis=0 → Join rows (default)
- axis=1 → Join columns

In [ ]:
# 1D Array
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

c=np.concat((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [5]:
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [6]:
# 2D Array
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

In [8]:
# Concatenate Rows (axis=0)
c=np.concat((a,b),axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
# Concatenate Columns (axis=1)
c=np.concat((a,b),axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [10]:
# 3D Array
a = np.array([
    [[1,2],[3,4]]
])

b = np.array([
    [[5,6],[7,8]]
])

print(a.shape)
# (1,2,2)

(1, 2, 2)


In [ ]:
# Concatenate Along Depth
# as a block
c=np.concat((a,b),axis=0)
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# as a row
c=np.concat((a,b),axis=1)
c

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [ ]:
# as a column
c=np.concat((a,b),axis=2)
c

array([[[1, 2, 5, 6],
        [3, 4, 7, 8]]])

In [ ]:
# Different Number of Rows
a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6]])

#np.concatenate((a,b), axis=2)    #ValueError
# For axis=1, the number of rows must be the same.

AxisError: axis 2 is out of bounds for array of dimension 2