In [1]:
import numpy as np

NumPy hsplit()
- hsplit() is used to split an array horizontally (column-wise).

Syntax
- np.hsplit(arr, indices_or_sections)

Parameters
- arr → Input array
- indices_or_sections
- Number of equal parts
- OR list of split indices

Rules
- ✅ Splits columns.
- ✅ Works only with 2D or higher-dimensional arrays.
- ✅ Number of columns must be divisible by the number of sections (for equal split).
- ✅ Returns a list of arrays.
- ✅ Original array is not modified.

In [2]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
b=np.hsplit(a,2)
b

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [5]:
print(a.shape)
print(b[0].shape)
print(b[0])
print(b[1])

(4, 2)
(4, 1)
[[1]
 [3]
 [5]
 [7]]
[[2]
 [4]
 [6]
 [8]]


In [6]:
# Split at Specific Columns
a = np.array([[1,2,3,4],
              [5,6,7,8]])

In [8]:
b=np.hsplit(a,2)
b

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [ ]:
#specific split
b=np.hsplit(a,[1,3])
b

[array([[1],
        [5]]),
 array([[2, 3],
        [6, 7]]),
 array([[4],
        [8]])]

In [11]:
# 3D array
a=np.arange(24).reshape(2,3,4)
a.shape

(2, 3, 4)

In [13]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
b=np.hsplit(a,2)
b

ValueError: array split does not result in an equal division

In [14]:
b=np.hsplit(a,3)
b

[array([[[ 0,  1,  2,  3]],
 
        [[12, 13, 14, 15]]]),
 array([[[ 4,  5,  6,  7]],
 
        [[16, 17, 18, 19]]]),
 array([[[ 8,  9, 10, 11]],
 
        [[20, 21, 22, 23]]])]

In [17]:
b=np.hsplit(a,[1,3])
b

[array([[[ 0,  1,  2,  3]],
 
        [[12, 13, 14, 15]]]),
 array([[[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([], shape=(2, 0, 4), dtype=int64)]