In [1]:
# 📌 Handling Missing Values in NumPy
# What are Missing Values? : Missing values are unknown, empty, or invalid data points that appear in real-world datasets.

# Examples:
# Student marks missing
# Sensor data failure
# Survey unanswered questions
# Corrupted files

# Special Missing Values in NumPy
# NumPy uses special floating-point values to represent missing/invalid data.

In [2]:
# Special Value	                   Meaning
# np.nan	                       Not a Number (missing value)
# np.inf	                       Positive infinity
# -np.inf                          Negative infinity

# 🔍 Why handling is required
# Reason	                    What happens if ignored
# Math becomes wrong	        mean, sum become NaN
# ML models fail	            Cannot train
# Graphs break	                Empty charts
# Decisions become wrong	    Wrong business result

In [ ]:
# 🔹 Detecting Missing Values
# Function	              Use
# np.isnan()	          Find NaN
# np.isinf()	          Find infinity
# np.isfinite()	          Valid numbers

# 🔹 Handling Techniques
# Method	                      Use
# Remove missing	              np.nan_to_num()
# Replace with 0	              Fill default
# Replace with mean	              Statistical filling
# Mask invalid	                  Ignore invalid
# Interpolation	                  Estimate values

In [ ]:
# 🧪 Replace NaN with 0
# np.nan_to_num(data)

# 🧪 Replace NaN with Mean
# clean = np.where(np.isnan(data), np.nanmean(data), data)

# 🧪 Remove NaN
# data[~np.isnan(data)]

# 🎯 Interview One-liner
# Missing values must be handled because NaN and Inf can break calculations and machine learning models.

# 🏁 Summary
# Concept	             Purpose
# np.nan	             Missing value
# np.inf	             Invalid infinite
# Handling	         Clean data for correct results

In [3]:
import numpy as np

In [4]:
# find nan

a = np.array([1,2,3,np.nan,4,5,np.nan])

print(np.isnan(a))

[False False False  True False False  True]


In [11]:
# can you compare 2 NaN values like (np.nan == np.nan)
# answer is no we cant comapre only need to use isnan()

In [ ]:
#replace 
#np.nan_to_num(array, nan = value) default = 0
b = np.nan_to_num(a)
print(b)
print(a)

[1. 2. 3. 0. 4. 5. 0.]
[ 1.  2.  3. nan  4.  5. nan]


In [6]:
b=np.nan_to_num(a,nan=100)
b

array([  1.,   2.,   3., 100.,   4.,   5., 100.])

In [7]:
a= np.array([1,2,3,np.inf,4,5,-np.inf,6,7])

print(np.isinf(a))

[False False False  True False False  True False False]


In [8]:
np.isposinf(a)

array([False, False, False,  True, False, False, False, False, False])

In [9]:
np.isneginf(a)

array([False, False, False, False, False, False,  True, False, False])

In [10]:
b=np.nan_to_num(a,posinf=100,neginf=-100)
b

array([   1.,    2.,    3.,  100.,    4.,    5., -100.,    6.,    7.])