In [1]:
print("a")

a


In [2]:
# NumPy insert()

# insert() is used to insert values at a specific position in an array.

# Syntax
# np.insert(arr, index, values, axis=None)
# Parameters
# arr → Original array
# index → Position where value is inserted
# values → Value(s) to insert
# axis → Dimension (optional)
# do not change original array

In [3]:
import numpy as np

In [4]:
# 1D Array
# Insert Single Value
a=np.array([1,2,3,4,5,6,7,8])
b=np.insert(a,2,100)
print(a)
print(b)

[1 2 3 4 5 6 7 8]
[  1   2 100   3   4   5   6   7   8]


In [5]:
# Insert Multiple Values
a=np.array([1,2,3,4,5,6,7,8])
b=np.insert(a,3,[11,22,33])
print(a)
print(b)

[1 2 3 4 5 6 7 8]
[ 1  2  3 11 22 33  4  5  6  7  8]


In [6]:
# 2D array insert row
a=np.array([[1,2],
            [3,4],
            [5,6],
            [7,8]])

b=np.insert(a,2,[11,22])
print(a)
print(b)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[ 1  2 11 22  3  4  5  6  7  8]


In [7]:
# 2D array insert row
a=np.array([[1,2],
            [3,4],
            [5,6],
            [7,8]])

b=np.insert(a,2,[11,22],axis=0)
print(a)
print("------")
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
------
[[ 1  2]
 [ 3  4]
 [11 22]
 [ 5  6]
 [ 7  8]]


In [8]:
# 2D array insert column
a=np.array([[1,2],
            [3,4],
            [5,6],
            [7,8]])

b=np.insert(a,1,[11,22,33,44],axis=1)
print(a)
print("------")
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
------
[[ 1 11  2]
 [ 3 22  4]
 [ 5 33  6]
 [ 7 44  8]]


In [9]:
# 3D insert 

a=np.array([[[1,2],
            [3,4]], 

            [[5,6],
            [7,8]], 

            [[9,10],
             [11,12]]])

a.shape

(3, 2, 2)

In [10]:
b=np.insert(a,2,[[99,88],[77,66]],axis=0)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[99, 88],
        [77, 66]],

       [[ 9, 10],
        [11, 12]]])

In [11]:
b=np.insert(a,2,[[99,88],[77,66],[55,44]],axis=1)
b

array([[[ 1,  2],
        [ 3,  4],
        [99, 88]],

       [[ 5,  6],
        [ 7,  8],
        [77, 66]],

       [[ 9, 10],
        [11, 12],
        [55, 44]]])

In [12]:
b=np.insert(a,2,[99],axis=1)
b

array([[[ 1,  2],
        [ 3,  4],
        [99, 99]],

       [[ 5,  6],
        [ 7,  8],
        [99, 99]],

       [[ 9, 10],
        [11, 12],
        [99, 99]]])

In [14]:
# b=np.insert(a,2,[[99,88],[77,66]],axis=1)
# b

In [15]:
# | Function    | Purpose                | Changes Original? |
# | ----------- | ---------------------- | ----------------- |
# | `insert()`  | Add element/row/column | ❌ No              |
# | `append()`  | Add at end             | ❌ No              |
# | `delete()`  | Remove elements        | ❌ No              |
# | `reshape()` | Change shape           | ❌ No              |
# | `resize()`  | Change shape & size    | ✅ (`arr.resize`)  |