In [1]:
print("a")

a


NumPy delete()

delete() is used to remove elements, rows, or columns from an array.<br>

Syntax<br>
- np.delete(arr, index, axis=None)<br>

Parameters<br>
- arr → Original array<br>
- index → Position(s) to delete<br>
- axis=None → Delete from flattened array (default)<br>
- axis=0 → Delete row<br>
- axis=1 → Delete column<br>

In [2]:
import numpy as np

In [ ]:
#  1D Array

# Delete Single Element
#            0  1  2  3  4  5  6 7
a=np.array([11,22,33,44,55,66,77,88])
b=np.delete(a,2)
print(b)
print(a)

[11 22 44 55 66 77 88]
[11 22 33 44 55 66 77 88]


In [6]:
# Delete Multiple Elements
#            0  1  2  3  4  5  6 7
a=np.array([11,22,33,44,55,66,77,88])

b= np.delete(a,[3,6])
print(b)
print(a)


[11 22 33 55 66 88]
[11 22 33 44 55 66 77 88]


In [8]:
# 2D Array
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [13]:
print(a[2][1])

8


In [14]:
# Delete Row

b=np.delete(a,0,axis=0)
b

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
b=np.delete(a,1,axis=0)
b

array([[1, 2, 3],
       [7, 8, 9]])

In [17]:
# delete column
b=np.delete(a,0,axis=1)
b

array([[2, 3],
       [5, 6],
       [8, 9]])

In [18]:
b=np.delete(a,1,axis=1)
b

array([[1, 3],
       [4, 6],
       [7, 9]])

In [19]:
a = np.array([
               [[1,2],
               [3,4]],

              [[5,6],
               [7,8]],

              [[9,10],
               [11,12]]
            ])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
a.shape

(3, 2, 2)

In [21]:
b=np.delete(a,0,axis=0)
b

array([[[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [22]:
b=np.delete(a,0,axis=1)
b

array([[[ 3,  4]],

       [[ 7,  8]],

       [[11, 12]]])