NumPy vsplit()
- vsplit() is used to split an array vertically (row-wise).

Syntax
- np.vsplit(arr, indices_or_sections)

Parameters
- arr → Input array
- indices_or_sections
- Number of equal parts
- OR list of split indices

Rules
- ✅ Splits rows.
- ✅ Works only with 2D or higher-dimensional arrays.
- ✅ Number of rows must be divisible by the number of sections (for equal split).
- ✅ Returns a list of arrays.
- ✅ Original array is not modified.

In [19]:
import numpy as np

In [20]:
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
a


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [21]:
a=np.array([[1,2,11],[3,4,11],[5,6,11],[7,8,11],[9,10,11]])
a

array([[ 1,  2, 11],
       [ 3,  4, 11],
       [ 5,  6, 11],
       [ 7,  8, 11],
       [ 9, 10, 11]])

In [22]:
b=np.hsplit(a,3)
b

[array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]]),
 array([[11],
        [11],
        [11],
        [11],
        [11]])]

In [23]:
# Split at Specific Columns
b=np.hsplit(a,[1])
b

[array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([[ 2, 11],
        [ 4, 11],
        [ 6, 11],
        [ 8, 11],
        [10, 11]])]

In [24]:
# b=np.vsplit(a,2)
# b

In [32]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [33]:
b=np.vsplit(a,2)
b

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])]

In [35]:
b=np.vsplit(a,[2])
b

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([], shape=(0, 3, 4), dtype=int64)]

In [ ]:
# array([[[ 0,  1,  2,  3],           [[12, 13, 14, 15],
#         [ 4,  5,  6,  7],            [16, 17, 18, 19],
#         [ 8,  9, 10, 11]],           [20, 21, 22, 23]]])

In [ ]:
# Interview Notes
# Function	            Splits Along	Axis
# split(arr, n, axis=0)	Rows	        0
# vsplit(arr, n)	        Rows	        0

# vsplit() is equivalent to:
# np.split(arr, n, axis=0)

# Memory Trick
# V = Vertical = Rows
# vsplit() = Split Rows

In [36]:
b=np.hsplit(a,[2])
b

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19]]]),
 array([[[ 8,  9, 10, 11]],
 
        [[20, 21, 22, 23]]])]

In [37]:
print(b[0])
print()
print(b[1])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[12 13 14 15]
  [16 17 18 19]]]

[[[ 8  9 10 11]]

 [[20 21 22 23]]]
