This is my first notebook

In [1]:
print("hello")

hello


In [2]:
print("python2")

python2


In [3]:
a=10
b=20
b
a

10

In [ ]:
#!pip install jupyter ipykernel

In [5]:
import sys
print(sys.executable)

d:\batches-folder\python\numpy8am\.venv\Scripts\python.exe


array -- list -- slow 
numpy  -- array 

In [ ]:

#find average
temperature = [32.2, 31.5,33,7,32.8,35.1]         #list

total =0 
for temp in temperature:
    total+=temp     # total = total+temp

average = total/len(temperature)    


In [5]:
average

28.599999999999998

In [ ]:
#!pip install numpy

  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)



[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [6]:
# how to define array with numpy 
temperatures = np.array([32.2, 31.5,33,7,32.8,35.1])
temperatures

array([32.2, 31.5, 33. ,  7. , 32.8, 35.1])

In [11]:
avg_temp = np.mean(temperatures)
print(avg_temp)

28.599999999999998


In [12]:
py_list=[1,2,3,4,5,6,7]
py_list

[1, 2, 3, 4, 5, 6, 7]

In [13]:
type(py_list)

list

In [14]:
np_array=np.array([1,2,3,4,5,6,7,8])
np_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
type(np_array)

numpy.ndarray

In [16]:
np_array.dtype

dtype('int64')

In [17]:
np_array2=np.array([1.2,3.4,5.6,6.7])
np_array2

array([1.2, 3.4, 5.6, 6.7])

In [18]:
np_array2.dtype

dtype('float64')

zeros()<br>
once()<br>
fill()<br>
empty()<br>

In [19]:
arr_z= np.zeros(3)
arr_z

array([0., 0., 0.])

In [20]:
arr_z.dtype

dtype('float64')

In [21]:
arr_z1=np.zeros(5, dtype=int)
arr_z1

array([0, 0, 0, 0, 0])

In [22]:
arr_z1.dtype

dtype('int64')

In [ ]:
#                r  c
arr_z2=np.zeros((2,3))
arr_z2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr_z2=np.zeros((3,2))
arr_z2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])