In [1]:
import numpy as np

In [2]:
nparr = np.array([1,2,3,4,5,6])
nparr

array([1, 2, 3, 4, 5, 6])

In [3]:
nparr.dtype

dtype('int64')

In [5]:
npz= np.zeros(3,int)
npz

array([0, 0, 0])

In [10]:
npz= np.zeros((4,5),int)
npz

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
onp= np.ones(5)
onp

array([1., 1., 1., 1., 1.])

In [7]:
onp= np.ones(5,int)
onp

array([1, 1, 1, 1, 1])

In [8]:
onp= np.ones((4,5))
onp

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
onp= np.ones((4,5),dtype=int)
onp

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
#fill array with other than 0 and 1
#full

fnp = np.full(4,3)
fnp

array([3, 3, 3, 3])

In [13]:
fnp = np.full((4,5),"a")
fnp

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [ ]:
# Why random values?

# np.empty() does not fill the array with zeros.

# It allocates memory and leaves whatever data was already present in that memory location.

# Think of it as:

# Allocate memory quickly
# Don't clean it
# Use whatever bytes are already there

In [ ]:
# np.empty(shape,dtype) : Create with random values

empty_arr = np.empty(5)
empty_arr

array([1., 1., 1., 1., 1.])

In [16]:
empty_arr = np.empty((5,3))
empty_arr

array([[6.23042070e-307, 4.67297004e-307, 1.69121096e-306],
       [1.33511290e-306, 6.23058368e-307, 2.22522597e-306],
       [1.33511969e-306, 1.37962320e-306, 9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306],
       [2.22522868e-306, 1.24611809e-306, 8.06632139e-308]])

In [17]:
empty_arr = np.empty((5,3),dtype=int)
empty_arr

array([[25895968444448782, 23925771418232211, 32370111954616435],
       [30962681234849884, 25896174606483567, 34058953225207854],
       [30962724186357876, 31244212048494684, 28429436511125606],
       [28710881422737503, 32651561162571873, 32370073300107356],
       [34058961815535732, 30399782823591982, 12666807751278697]])

In [ ]:
#create sequence of array in numpy 
#explain Range

# arange(start,stop(not included),step)

In [19]:
arr1 = np.arange(1,21,1)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
arr1 = np.arange(21)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [23]:
# arr1 = np.arange()
# arr1

In [24]:
arr1 = np.arange(2,21,2)
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
arr1 = np.arange(3,31,3)
arr1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [26]:
arr1 = np.arange(1,11,0.2)
arr1

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8])

In [27]:
arr1 = np.arange(1,11,2.5)
arr1

array([1. , 3.5, 6. , 8.5])

In [28]:
arr1 = np.arange(10,-1,-1)
arr1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [29]:
arr1 = np.arange(20,1,-2)
arr1

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [30]:
arr1 = np.arange(50,4,-5)
arr1

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [ ]:
#creating identity matrix

# 🔹 What is an Identity Matrix?
# An identity matrix is a square matrix where:
# All diagonal elements = 1
# All other elements = 0

#3*3 
# [1 0 0]
# [0 1 0]
# [0 0 1]

In [32]:
i_matrix = np.eye(3)
i_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
i_matrix = np.eye(3, dtype=int)
i_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [37]:
# i_matrix = np.eye((2,3),dtype=int)
# i_matrix

In [40]:
i_matrix = np.eye(2,3,dtype=int)
i_matrix

array([[1, 0, 0],
       [0, 1, 0]])

In [41]:
i_matrix = np.eye(5,3,dtype=int)
i_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

| Function      | Default dtype                  |
|---------------|--------------------------------|
| `np.zeros()`  | `float64`                      |
| `np.ones()`   | `float64`                      |
| `np.eye()`    | `float64`                      |
| `np.arange()` | Depends on input arguments     |
| `np.full()`   | Inferred from the fill value   |

In [46]:
#fancy indexing
arr = np.array([10,20,30,40,50,50,70,80])
arr[[0,2,4]]
#arr[[0,2,4,6,8,10]]
arr[[0,2,4,6]]

array([10, 30, 50, 70])