In [ ]:
# An array is a data structure that stores values of same data type (homogeneous).
# List store elements of different data type

# We can create NumPy arrays by converting a list/Tuple to an array.

# NumPy operations are faster than standard Python lists.

# we cannot apply mathematical operators directly on lists. element-wise operations with lists require a bunch of code
# we can apply mathematical operators directly on Array

In [3]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
npa = np.array([1,2,3,4,5])
npa

array([1, 2, 3, 4, 5])

In [5]:
npa

array([1, 2, 3, 4, 5])

In [6]:
lst=list(range(1,11))
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
len(npa)
len(lst)

10

In [10]:
type(npa)
type(lst)

list

In [11]:
tup = tuple(lst)
tup

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [12]:
np.array(tup)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#list+2

In [15]:
lst2 = []
for x in lst:
    lst2.append(x+2)
lst2    

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [18]:
add_npa = npa + 2
add_npa

array([3, 4, 5, 6, 7])

In [17]:
npa*2

array([ 2,  4,  6,  8, 10])

- List store elements of different data type (Mixed datatype)
- Array store elements of same data type (homogeneous)

In [19]:
lst2 = [1,2,True,"python",2.0,]
lst2

[1, 2, True, 'python', 2.0]

In [22]:
type(lst2[4])

float

In [23]:
npa2 = np.array(lst2)
npa2

array(['1', '2', 'True', 'python', '2.0'], dtype='<U32')

In [26]:
type(npa2[4])

numpy.str_

In [27]:
npa3 = np.array([1,2,3,4,5,6,7],dtype=str)
npa3

array(['1', '2', '3', '4', '5', '6', '7'], dtype='<U1')

In [28]:
npa3 = np.array([1,2,3,4,5,6,7],dtype=float)
npa3

array([1., 2., 3., 4., 5., 6., 7.])

In [29]:
npa3 = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7],dtype=int)
npa3

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
npa3 = np.array([-1,0,1,2,3,4,5,6,7],dtype=bool)
npa3

array([ True, False,  True,  True,  True,  True,  True,  True,  True])

In [39]:
npa3.dtype

dtype('bool')

In [33]:
npa3 = np.array([1,2,3,4,5,6,7],dtype=complex)
npa3

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [42]:
npa3 = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7])

In [43]:
type(npa3)

numpy.ndarray

In [44]:
npa3.dtype

dtype('float64')

In [46]:
npa3

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7])

In [ ]:
# Convert Float Array to Integer
arr_int=npa3.astype(int)
print(arr_int)
print(arr_int.dtype)

[1 2 3 4 5 6 7]
int64


In [ ]:
# Convert Float Array to String
arr_str=arr_int.astype(str)
print(arr_str)
print(arr_str.dtype)

['1' '2' '3' '4' '5' '6' '7']
<U21


In [50]:
# Convert Float Array to float
arr_flt=arr_str.astype(float)
print(arr_flt)
print(arr_flt.dtype)

[1. 2. 3. 4. 5. 6. 7.]
float64


In [57]:
#str = np.array(['a','b','c','d'])
str = np.array(['1','2','3','4'])

In [58]:
arr_flt2=str.astype(float)
print(arr_flt2)
print(arr_flt2.dtype)

# could not convert string to float: np.str_('a')

[1. 2. 3. 4.]
float64


In [59]:
arr_int2=str.astype(int)
print(arr_int2)
print(arr_int2.dtype)

#invalid literal for int() with base 10: np.str_('a')

[1 2 3 4]
int64


In [61]:
arr_cpx2=str.astype(complex)
print(arr_cpx2)
print(arr_cpx2.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128
