## indexing / Slicing

In [ ]:
#       0   1   2   3    4   5   6   7   8   9    ==> Positive Index
#     [ 1   2   3   4   5   6   7   8   9   10]  ==> Left to right
#     -10  -9  -8  -7  -6  -5  -4  -3  -2   -1   ==> Negative Index

In [ ]:
# variable  [start :       end :              step]
#           0         len(variable)          1     ==> By default
#   ================== Left to Right =====================>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[::]  #whole array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[::2]

array([1, 3, 5, 7, 9])

In [ ]:
a[1::2]

In [5]:
a[1:8:3]

array([2, 5, 8])

In [6]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [7]:
a[1::-1]

array([2, 1])

In [8]:
a[0::-1]

array([1])

In [ ]:
#       0   1   2   3    4   5   6   7   8   9    ==> Positive Index
#     [ 1   2   3   4   5   6   7   8   9   10]  ==> Left to right
#     -10  -9  -8  -7  -6  -5  -4  -3  -2   -1   ==> Negative Index

In [9]:
a[-4:-1:-1]

array([], dtype=int64)

In [10]:
a[-4:-1:1]

array([7, 8, 9])

In [13]:
a[-9: -2:2]

array([2, 4, 6, 8])

In [14]:
a[-10:5:2]

array([1, 3, 5])

### Mutability

In [15]:
str="dipanshu"
str

'dipanshu'

In [16]:
str[2]

'p'

In [20]:
#str[2]="z"
#TypeError: 'str' object does not support item assignment

In [21]:
list =['d','i','p','a','n','s','h','u']
list

['d', 'i', 'p', 'a', 'n', 's', 'h', 'u']

In [22]:
list[2]

'p'

In [24]:
list[2]='z'
list

['d', 'i', 'z', 'a', 'n', 's', 'h', 'u']

In [25]:
npa = np.array([1,2,3,4,5,6,7,8])
npa

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
npa[2]

np.int64(3)

In [29]:
npa[2]=99
npa

array([ 1,  2, 99,  4,  5,  6,  7,  8])

In [30]:
npa[-1]=100
npa

array([  1,   2,  99,   4,   5,   6,   7, 100])

In [32]:
npa[-5]=200
npa

array([  1,   2,  99, 200,   5,   6,   7, 100])

### loops

In [33]:
for x in npa:
    print(x)

1
2
99
200
5
6
7
100
