##### Create array using np.arange() function
- Returns an array with evenly spaced elements as per the step size(by default 1)
- It has the following paramaters:
  * start : start of interval range. By default start = 0
  * stop  : end of interval range
  * step  : step size of interval. By default step size = 1
- Fractional step count is allowed in arange. Fractional stepsize not allowed in range.

In [ ]:
# Syntax: 
#  np.arange(start,      end,    stepsize,   dtype)
#           optional            optional   optional
#              0                   +1
                               # fractional step count is allowed 

In [1]:
import numpy as np

In [2]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(2,21,2))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [5]:
list(range(20,1,-2))

[20, 18, 16, 14, 12, 10, 8, 6, 4, 2]

In [7]:
# list(range(1,20,2.5))
# #TypeError: 'float' object cannot be interpreted as an integer

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 21 ,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
np.arange(20,1,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [11]:
np.arange(1,20,2.5)

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5])

In [12]:
np.arange(1,20,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

In [21]:
a=np.arange(1,20,0.7,dtype=int)     #step size  =  0.5 int==> 0
#This happens because NumPy first casts the step value 0.5 to the requested dtype (int), making it:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [22]:
len(a)

28

In [ ]:
np.arange(1,20,1.5,dtype=int)    #step size = 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [26]:
len(np.arange(1,20,1.5,dtype=int) )

13

In [24]:
np.arange(1,20,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. , 14.5, 16. ,
       17.5, 19. ])

In [25]:
len(np.arange(1,20,1.5))

13

In [23]:
np.arange(1,20,2,dtype=float)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [28]:
# np.arange(1,20,2,dtype=str)
# #TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [31]:
np.arange(2,21,2,float)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [32]:
np.arange(1,20,2.5,int)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [33]:
np.arange(dtype=int,step=2, stop=20, start=10)

array([10, 12, 14, 16, 18])

In [34]:
np.arange(step=2, stop=20,dtype=int, start=10)

array([10, 12, 14, 16, 18])

##### Create array Using np.linspace() function
- Returns evenly spaced numbers over a specified interval. Here the start and stop both are included.            
- It has the following parameters:              
    - start: start of interval range.
    - stop: end of interval range
    - num : No. of samples to generate. By default num = 50

In [ ]:
#Syntax :- 
#np.linspace(start, stop,  num,    endpoint=True,    retstep=False)
#                         (part)   include/exclud    Gives stepsize
#                        optional    optional        optional
#                          50          True            False

In [39]:
x= np.linspace(1,20)
x

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [40]:
len(x)

50

In [41]:
x= np.linspace(1,20,retstep=True)
x

(array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
         2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
         4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
         6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
         8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
        10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
        12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
        14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
        16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
        18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ]),
 np.float64(0.3877551020408163))

In [45]:
x= np.linspace(1,20,10)
x

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [42]:
x= np.linspace(1,20,10,retstep=True)
x

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
        11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]),
 np.float64(2.111111111111111))

In [43]:
x= np.linspace(2,20,10,retstep=True)
x

(array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]), np.float64(2.0))

In [44]:
x= np.linspace(2,20,10,endpoint=False,retstep=True)
x

(array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2]),
 np.float64(1.8))