Reshape : Change shape of array<br>
M1<br>
- Array.reshape(shape,Fill_by)
- shape= (row,col)
- Fill_by "C" ===> Fill_by Row
-          "F" ===> Fill_by column

M2<br>
- np.reshape(data,shape,order(Fill_by))
- shape= (row,col)
- order (Fill_by) "C" ===> Fill_by Row
-          "F" ===> Fill_by column

- resshape(rows, columns) specify new shape if dimensions match

- np.reshape() returns a new reshaped view (or copy), it does NOT modify the original array in-place.

- If values is less than new shape we got error (but size fills zeros)

In [30]:
import numpy as np

In [31]:
npa = np.array([1,2,3,4,5,6,7,8])
npa

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
npa.shape

(8,)

M1<br>
- Array.reshape(shape,Fill_by)
- shape= (row,col)
- Fill_by "C" ===> Fill_by Row
-          "F" ===> Fill_by column

In [33]:
npa.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
npa.reshape((2,4),order="F")

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [35]:
npa.reshape((4,2),order="c")

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
npa.reshape((4,2),order="F")

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [37]:
#npa.reshape(3,4)

In [38]:
npa2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [39]:
new_arr = npa2.reshape((3,4),order="f")
new_arr

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

M2<br>
- np.reshape(data,shape,order(Fill_by))
- shape= (row,col)
- order (Fill_by) "C" ===> Fill_by Row
-          "F" ===> Fill_by column

In [40]:
npa2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
npa2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
new_a2= np.reshape(npa2,(3,4),order="f")
new_a2

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [42]:
new_a2= np.reshape(npa2,(6,2),order="f")
new_a2

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [43]:
npa2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
new_a2= np.reshape(npa2,(2,6),order="f")
new_a2

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [45]:
# new_a2= np.reshape(npa2,(4,4),order="f")
# new_a2
#ValueError: cannot reshape array of size 12 into shape (4,4)

In [46]:
new_a2.shape

(2, 6)

In [56]:
npa2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
npa2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
npa2.resize(2,6)
npa2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [58]:
npa2.resize(3,4)
npa2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
npa3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
npa3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
npa3.resize((3,4))
npa3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
npa4=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
npa4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
# npa4.resize((2,7))
# ValueError: cannot resize an array that references or is referenced
# by another object in this way.

In [73]:
new_a2=np.resize(npa4,(2,7))
new_a2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12,  1,  2]])

In [66]:
arr = np.array([1,2,3,4,5,6,7,8])
arr.resize((4,3))  
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 0]
 [0 0 0]]


In [ ]:
# | Function       | In-place?           | Can change size? | Fills with 0?      |
# | -------------- | ------------------- | ---------------- | ------------------ |
# | `reshape()`    | ❌ No                | ❌ No             | N/A                |
# | `arr.resize()` | ✅ Yes               | ✅ Yes            | ✅ Yes              |
# | `np.resize()`  | ❌ Returns new array | ✅ Yes            | ❌ Repeats elements |
