In [ ]:
# np.pad() is the safe and professional way to add extra values around an array.
# It is much better than resize() for padding.

# 🔹 np.pad() — Add values around array
# 📌 Syntax
# np.pad(array, pad_width, mode='constant', constant_values=0)

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])

In [6]:
b=np.pad(a,(2,3))
b

array([0, 0, 1, 2, 3, 4, 0, 0, 0])

In [5]:
b.size

9

In [7]:
np.pad(a,(2,3),constant_values=9)

array([9, 9, 1, 2, 3, 4, 9, 9, 9])

In [8]:
np.pad(a,5)

array([0, 0, 0, 0, 0, 1, 2, 3, 4, 0, 0, 0, 0, 0])

In [11]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
np.pad(x,2)     #add 2 rows befor and after and 2 columns befor and after in each row

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0, 0],
       [0, 0, 3, 4, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [13]:
np.pad(x,2,constant_values=8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 1, 2, 8, 8],
       [8, 8, 3, 4, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [ ]:
#         b a
np.pad(x,(2,3))

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0, 0, 0],
       [0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
#          b a   b  a 
#           r     c
np.pad(x,((3,1),(4,3)))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
np.pad(x,((3,1),(4,3)),constant_values=7)

array([[7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 1, 2, 7, 7, 7],
       [7, 7, 7, 7, 3, 4, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7]])