In [3]:
import numpy as np

In [4]:
#reshapr , resize , padd

In [5]:
a=np.array([1,2,3,4,5,6])

In [6]:
#NumPy reshape(), resize() and pad()

# 1. reshape() - Change Shape (Elements must match) - do not change original array
# 1D → 2D
# --------

# Method 1 ==>
#--------------
#           r c
b=a.reshape(2,3)
print(b)
print(a)




[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [7]:
c=a.reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# d=a.reshape(3,3)           #3*3 = 9
# d

In [9]:
# Method 2 ==>
d=np.reshape(a,(2,3))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
d=np.reshape(a,(3,2))
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
# 1D ==> 3D
a=np.array([1,2,3,4,5,6,7,8])
#            b r c
e =a.reshape(2,2,2)
e

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#            b r c
e =a.reshape(3,2,2)
e

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#            b r c
e =a.reshape((4,1,3),order="c")
e

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [14]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#            b r c
e =a.reshape((4,1,3),order="f")
e

array([[[ 1,  5,  9]],

       [[ 2,  6, 10]],

       [[ 3,  7, 11]],

       [[ 4,  8, 12]]])

In [15]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#            b r c
e =a.reshape(4,1,3)
e

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [16]:
# 2. resize() - Change Shape and Size 

# array.resize() - changes original array.
# np.resize() - does NOT modify the original array.

In [17]:
# Method 1 : arr.resize(shape)
# ------------------------------
# Changes original array
# Extra positions filled with 0
a=np.array([1,2,3,4,5,6])
a.resize((3,3))
a


array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [18]:
a=np.array([1,2,3,4,5,6])
a.resize((4,5))
a

array([[1, 2, 3, 4, 5],
       [6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
# Method 2: np.resize(array, shape)
# ---------------------------------
# Does NOT change original array
# Returns a new array
# Extra positions filled by repeating existing values

In [20]:
a=np.array([1,2,3,4,5,6])
b=np.resize(a,(3,3))
print(b)
print(a)

[[1 2 3]
 [4 5 6]
 [1 2 3]]
[1 2 3 4 5 6]


In [21]:
a=np.array([1,2,3,4,5,6])
b=np.resize(a,(5,6))
print(b)


[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [22]:
# np.pad() is the safe and professional way to add extra values around an array.
# It is much better than resize() for padding.

# 🔹 np.pad() — Add values around array
# 📌 Syntax
# np.pad(array, pad_width, mode='constant', constant_values=0)

In [23]:
# 1D array

In [24]:
a=np.array([1,2,3,4,5,6])
#           b a             
b=np.pad(a,(2,3))
b

array([0, 0, 1, 2, 3, 4, 5, 6, 0, 0, 0])

In [25]:
a=np.array([1,2,3,4,5,6])
b=np.pad(a,(2,3),constant_values=8)
b

array([8, 8, 1, 2, 3, 4, 5, 6, 8, 8, 8])

In [26]:
c=np.pad(a,(3,3),constant_values=7)
c

array([7, 7, 7, 1, 2, 3, 4, 5, 6, 7, 7, 7])

In [27]:
a

array([1, 2, 3, 4, 5, 6])

In [29]:
# c=np.pad(a,((2,2),(3,3)),constant_values=8)
# c

In [ ]:
# 2D padding
a=np.array([[1,2],[3,4]])

#             r     c          (row   column)
#            b a   b  a        (before after)
b=np.pad(a,((1,2),(2,3)))
b
#Meaning: ((top,bottom), (left,right))

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0, 0, 0],
       [0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# 3D padding
a=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
a.shape

(2, 2, 2)

In [ ]:
#            b       r     c          (block, row   column)
#            b  a  b a   b  a        (before after)
b=np.pad(a,((1,1),(1,2),(2,3)))
b
# Meaning:((depth_before,depth_after), (rows_before,rows_after), (cols_before,cols_after))

array([[[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 2, 0, 0, 0],
        [0, 0, 3, 4, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 2, 0, 0, 0],
        [0, 0, 3, 4, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]])

In [36]:
# np.pad(array, pad_width, mode='constant', constant_values=0)

In [39]:
# 1. mode='constant' (Default) : Adds the same value around the array.
# --------------------------------------------------------------------

In [ ]:
# 2. mode='edge' : Repeats edge values
# ------------------------------------
a=np.array([11,2,3,4,5,66])
b=np.pad(a,(2,3),mode='edge')
b

array([11, 11, 11,  2,  3,  4,  5, 66, 66, 66, 66])

In [40]:
# 3. mode='wrap' : # Wraps values from the opposite side.
# ------------------------------------------------------
a=np.array([11,2,3,4,5,66])
b=np.pad(a,(2,3),mode='wrap')
b

array([ 5, 66, 11,  2,  3,  4,  5, 66, 11,  2,  3])

In [41]:
# 4. mode='reflect' : Reflects values without repeating edge. (mirrer efect)
# ---------------------------------------------------------------------------
a=np.array([11,2,3,4,5,66])
b=np.pad(a,(2,3),mode='reflect')
b

array([ 3,  2, 11,  2,  3,  4,  5, 66,  5,  4,  3])

In [42]:
# 5. mode='symmetric' : Reflects values including edge.
# --------------------------------------------------------
a=np.array([11,2,3,4,5,66])
b=np.pad(a,(2,3),mode='symmetric')
b

array([ 2, 11, 11,  2,  3,  4,  5, 66, 66,  5,  4])

In [ ]:
# Important Note
# ---------------
# np.pad(arr,pad_width,mode='constant',constant_values=value)

# pad_width → How many values to add.
# mode → How to fill added values.
# constant_values → Used only with mode='constant'.

# Most Common Interview Modes
# | Mode        | Behavior                  |
# | ----------- | ------------------------- |
# | `constant`  | Fill with fixed value     |
# | `edge`      | Repeat edge values        |
# | `wrap`      | Repeat from opposite side |
# | `reflect`   | Mirror without edge       |
# | `symmetric` | Mirror with edge          |


# For beginners, remember: constant, edge, reflect, wrap are the four modes most commonly used in practice.
