In [2]:
import numpy as np

In [3]:
#reshapr , resize , padd

In [4]:
a=np.array([1,2,3,4,5,6])

In [ ]:
#NumPy reshape(), resize() and pad()

# 1. reshape() - Change Shape (Elements must match) - do not change original array
# 1D → 2D
# --------

# Method 1 ==>
#--------------
#           r c
b=a.reshape(2,3)
print(b)
print(a)




[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [7]:
c=a.reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
# d=a.reshape(3,3)           #3*3 = 9
# d

In [10]:
# Method 2 ==>
d=np.reshape(a,(2,3))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
d=np.reshape(a,(3,2))
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# 1D ==> 3D
a=np.array([1,2,3,4,5,6,7,8])
#            b r c
e =a.reshape(2,2,2)
e

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#            b r c
e =a.reshape(3,2,2)
e

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [22]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#            b r c
e =a.reshape((4,1,3),order="c")
e

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [23]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#            b r c
e =a.reshape((4,1,3),order="f")
e

array([[[ 1,  5,  9]],

       [[ 2,  6, 10]],

       [[ 3,  7, 11]],

       [[ 4,  8, 12]]])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#            b r c
e =a.reshape(4,1,3)
e

In [ ]:
# 2. resize() - Change Shape and Size 

# array.resize() - changes original array.
# np.resize() - does NOT modify the original array.

In [16]:
# Method 1 : arr.resize(shape)
# ------------------------------
# Changes original array
# Extra positions filled with 0
a=np.array([1,2,3,4,5,6])
a.resize((3,3))
a


array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [17]:
a=np.array([1,2,3,4,5,6])
a.resize((4,5))
a

array([[1, 2, 3, 4, 5],
       [6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# Method 2: np.resize(array, shape)
# ---------------------------------
# Does NOT change original array
# Returns a new array
# Extra positions filled by repeating existing values

In [18]:
a=np.array([1,2,3,4,5,6])
b=np.resize(a,(3,3))
print(b)
print(a)

[[1 2 3]
 [4 5 6]
 [1 2 3]]
[1 2 3 4 5 6]


In [ ]:
a=np.array([1,2,3,4,5,6])
b=np.resize(a,(5,6))
print(b)


[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [ ]:
# np.pad() is the safe and professional way to add extra values around an array.
# It is much better than resize() for padding.

# 🔹 np.pad() — Add values around array
# 📌 Syntax
# np.pad(array, pad_width, mode='constant', constant_values=0)

In [24]:
a=np.array([1,2,3,4,5,6])
b=np.pad(a,(2,3))
b

array([0, 0, 1, 2, 3, 4, 5, 6, 0, 0, 0])

In [25]:
a=np.array([1,2,3,4,5,6])
b=np.pad(a,(2,3),constant_values=8)
b

array([8, 8, 1, 2, 3, 4, 5, 6, 8, 8, 8])

In [28]:
c=np.pad(a,(3,3),constant_values=7)
c

array([7, 7, 7, 1, 2, 3, 4, 5, 6, 7, 7, 7])

In [32]:
a

array([1, 2, 3, 4, 5, 6])

In [33]:
# c=np.pad(a,((2,2),(3,3)),constant_values=8)
# c