ravel() vs flatten()

Both are used to convert a multi-dimensional array into a 1D array.

##### ravel() --- view (changes original array)
##### flatten()---copy (make a copy and original array is unchanged)

##### Both convert a multi-dimensional array into a 1-D array, but the memory behavior is different.

In [1]:
# 📌 Definitions
# Function	         What it does	                                Memory behavior
# ravel()	         Returns a flattened view (if possible)	        Shares memory
# flatten()	         Returns a flattened copy	                    New memory

In [2]:
import numpy as np

In [ ]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

[1 2 3 4 5 6]


In [ ]:
# Function	         What it does	                                Memory behavior
# ravel()	         Returns a flattened view (if possible)	        Shares memory
b=a.ravel()
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [12]:
b[1]=99
b

array([ 1, 99,  3,  4,  5,  6])

In [13]:
a

array([[ 1, 99,  3],
       [ 4,  5,  6]])

In [15]:
print(a[1][1])

5


In [16]:
a[1][1]=100
a

array([[  1,  99,   3],
       [  4, 100,   6]])

In [17]:
b

array([  1,  99,   3,   4, 100,   6])

In [18]:
# flatten()	         Returns a flattened copy	                    New memory
x=np.array([[11,22],[33,44],[55,66],[77,88]])
y=x.flatten()
print(x)
print(y)

[[11 22]
 [33 44]
 [55 66]
 [77 88]]
[11 22 33 44 55 66 77 88]


In [19]:
x[0][0]=100
x

array([[100,  22],
       [ 33,  44],
       [ 55,  66],
       [ 77,  88]])

In [20]:
y

array([11, 22, 33, 44, 55, 66, 77, 88])

In [22]:
y[0]=999
y

array([999,  22,  33,  44,  55,  66,  77,  88])

In [23]:
x

array([[100,  22],
       [ 33,  44],
       [ 55,  66],
       [ 77,  88]])

In [ ]:
# Syntax

# arr.flatten(order='C')
# Order
# 'C' → Row-wise (default)
# 'F' → Column-wise

In [ ]:
x=np.array([[11,22],[33,44],[55,66],[77,88]])
y=x.flatten(order='C')              #c= row
print(x) 
print(y)

[[11 22]
 [33 44]
 [55 66]
 [77 88]]
[11 22 33 44 55 66 77 88]


In [27]:
x=np.array([[11,22],[33,44],[55,66],[77,88]])
y=x.flatten(order='F')             # F =column
print(x)
print(y)

[[11 22]
 [33 44]
 [55 66]
 [77 88]]
[11 33 55 77 22 44 66 88]


In [28]:
# Quick Notes
# ravel()
# -------
# - Converts ND → 1D
# - Returns View (usually)
# - Faster
# - Less memory

# flatten()
# ---------
# - Converts ND → 1D
# - Returns Copy
# - Slower
# - More memory


# | Feature                     | ravel()   | flatten() |
# | --------------------------- | --------- | --------- |
# | Converts to 1D              | ✅         | ✅         |
# | Returns View                | ✅ Usually | ❌         |
# | Returns Copy                | ❌         | ✅         |
# | Memory Efficient            | ✅         | ❌         |
# | Changes may affect original | ✅         | ❌         |


# One-Line Memory Trick
# ravel()   = View
# flatten() = Copy